"use client";
import { useState, useTransition } from "react";
import { updateTownOperations } from "@/app/actions";
import type { Town } from "@/types/database";

export function TownOperationsForm({ town }: { town: Town }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null); const c = "rounded-lg border border-hairline bg-[var(--color-surface)] p-2 text-sm";
  return <form action={(data) => startTransition(async () => { const r = await updateTownOperations(data); setMessage(r.ok ? "Saved." : r.error); })} className="grid gap-3 rounded-2xl border border-hairline bg-surface-raised p-5 sm:grid-cols-2 lg:grid-cols-4"><input type="hidden" name="town_id" value={town.id} /><label className="grid gap-1 text-xs">Pickup address<input name="pickup_address" defaultValue={town.pickup_address ?? ""} className={c} /></label><label className="grid gap-1 text-xs">Google Maps URL<input name="maps_url" type="url" defaultValue={town.maps_url ?? ""} className={c} /></label><label className="grid gap-1 text-xs">Delivery fee<input name="delivery_fee" type="number" min="0" defaultValue={town.delivery_fee} className={c} /></label><label className="grid gap-1 text-xs">Collection fee<input name="collection_fee" type="number" min="0" defaultValue={town.collection_fee} className={c} /></label><label className="grid gap-1 text-xs">Radius km<input name="delivery_radius_km" type="number" min="0" defaultValue={town.delivery_radius_km} className={c} /></label><label className="grid gap-1 text-xs">Opens<input name="opening_time" type="time" defaultValue={town.opening_time?.slice(0,5)} className={c} /></label><label className="grid gap-1 text-xs">Closes<input name="closing_time" type="time" defaultValue={town.closing_time?.slice(0,5)} className={c} /></label><button disabled={pending} className="self-end rounded-lg bg-[var(--color-brand-700)] p-2.5 text-sm font-semibold text-white">Save town</button>{message && <span className="self-center text-xs text-ink-faint">{message}</span>}</form>;
}
