"use client";
import { useState, useTransition } from "react";
import { updateVehicleDetails } from "@/app/actions";
import type { Vehicle } from "@/types/database";

export function VehicleDetailsForm({ vehicle }: { vehicle: Vehicle }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  const c = "rounded-lg border border-hairline bg-[var(--color-surface)] p-2 text-xs";
  return <details><summary className="cursor-pointer text-xs font-semibold text-[var(--color-brand-700)]">Edit specs</summary><form action={(data) => startTransition(async () => { const r = await updateVehicleDetails(data); setMessage(r.ok ? "Saved." : r.error); })} className="mt-2 grid w-72 gap-2 rounded-xl border border-hairline bg-surface-raised p-3 shadow-lift"><input type="hidden" name="vehicle_id" value={vehicle.id} /><select name="fuel_type" defaultValue={vehicle.fuel_type ?? ""} className={c}><option value="">Fuel</option><option value="petrol">Petrol</option><option value="diesel">Diesel</option><option value="electric">Electric</option><option value="cng">CNG</option></select><select name="transmission" defaultValue={vehicle.transmission ?? ""} className={c}><option value="">Transmission</option><option value="manual">Manual</option><option value="automatic">Automatic</option><option value="gearless">Gearless</option></select><input name="seats" type="number" placeholder="Seats" defaultValue={vehicle.seats ?? ""} className={c} /><input name="included_km_per_day" type="number" placeholder="Included km/day" defaultValue={vehicle.included_km_per_day ?? ""} className={c} /><input name="extra_km_rate" type="number" placeholder="Extra km price" defaultValue={vehicle.extra_km_rate ?? ""} className={c} /><input name="helmet_count" type="number" placeholder="Helmets" defaultValue={vehicle.helmet_count} className={c} /><input name="luggage_capacity" placeholder="Luggage capacity" defaultValue={vehicle.luggage_capacity ?? ""} className={c} /><input name="last_inspected_at" type="date" defaultValue={vehicle.last_inspected_at ?? ""} className={c} /><button disabled={pending} className="rounded-lg bg-[var(--color-brand-700)] p-2 text-xs font-semibold text-white">Save specs</button>{message && <span className="text-xs text-ink-faint">{message}</span>}</form></details>;
}
